// inApp.idl : IDL source for inApp
//

// This file will be processed by the MIDL tool to
// produce the type library (inApp.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(2902C105-7295-4C8F-A5B6-8FDCBAC8CA33),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IAdManager : IDispatch{
	[id(1)] HRESULT init(void);
	[id(2)] HRESULT showAdBanner(void);
};
[
	uuid(E7BA7C92-49E2-4121-B2A8-A72FF4F3A304),
	version(1.0),
]
library inAppLib
{
	importlib("stdole2.tlb");
	[
		uuid(AAC2E11A-2E64-4B54-9334-3FC8DC890E84)		
	]
	coclass AdManager
	{
		[default] interface IAdManager;
	};
};

